name: '1️⃣2️⃣3️⃣ VERSION from tag'
description: 'sets VERSION environment variable from tag'
outputs:
  version:
    value: ${{ steps.get-version.outputs.version}}
  success:
    value: ${{ steps.get-version.outputs.success}}
runs:
  using: "composite"
  steps:
    - id: get-version      
      shell: bash
      run: |
        echo $GITHUB_REF
        TEMP=$(echo $GITHUB_REF | grep -oE "[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9]+)?$")
        SUCCESS=$([ -z "$TEMP" ] && echo "false" || echo "true")
        echo $TEMP
        echo $SUCCESS
        echo "VERSION=${TEMP}" >> $GITHUB_ENV
        echo "::set-output name=version::$(echo $TEMP)"
        echo "::set-output name=success::$(echo $SUCCESS)"
