name: CI-CD

on:
  push:
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]
    branches: [ '**' ] 
  pull_request:
    branches: [ '**' ]
    types: [opened, synchronize, reopened, edited]

defaults:
  run:
    working-directory: src

jobs:
  test:
    name: 🛠 Build, 🧪 Test
    runs-on: ubuntu-latest
    
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🟣 Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: 🌴 dotnet restore
        run: dotnet restore

      - name: 🛠 dotnet build
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 dotnet test
        run: dotnet test --configuration Release --no-restore

  publish:
    name: 📦 Publish to NuGet
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/') && needs.test.result == 'success'

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      
      - name: 1️⃣2️⃣3️⃣ Set VERSION
        uses: ./.github/actions/version

      - name: 🟣 Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: 📦 Pack
        run: dotnet pack --configuration Release -p:Version=$VERSION

      - name: 🚀 Push
        run: dotnet nuget push **.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
