name: .NET Core

on:
  push:
    branches: [ master ]
    
jobs:
  deploy-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Projektanker.Icons.Avalonia
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build      
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
    - name: Nuget Push
      run: dotnet nuget push **.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  
  deploy-font-awesome:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Projektanker.Icons.Avalonia.FontAwesome
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore    
    - name: Build      
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
    - name: Nuget Push
      run: dotnet nuget push **.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      
