name: .NET Core

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: checkout FontAwesome
      uses: actions/checkout@v2
      with:
        repository: FortAwesome/Font-Awesome
        path: src/Avalonia.Icons.FontAwesome/font-awesome
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
        working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
        working-directory: src
